### ISSUE TITLE
How reduce the height of rows in tables

### ISSUE THREAD

**Issue by BigbadHort** [juracy/obsidian-asciidoc-blocks#1]
Thank you for the great plugin! With your plugin, working with tables has reached a new level.  Please tell me if I can somehow reduce the height of rows in tables?

**Comment by pkb** [comment]
@BigbadHort, while you are waiting for the solution from author, You may try to experiment with the following css snippet:
```css
.tableblock tr { line-height: 14px; }
p.tableblock {
    margin-block-start: 0px;
}
```
