### ISSUE TITLE
Default table border

### ISSUE THREAD

**Issue by dolandemort** [juracy/obsidian-asciidoc-blocks#2]
In your `styles.css` for this plugin, you set the following:

```css
.asciidoc-blocks-parent table.tableblock,
th.tableblock,
td.tableblock {
    border: 0 solid #dedede
}
```

I propose changing this to:

```css
.asciidoc-blocks-table-parent :is(th, td) {
  border: var(--table-border-width) solid var(--table-border-color);
}
```

This makes the border size/color respect whatever the active theme has set, and it also respects light/dark mode.
